[package]
name = "clip-to-mpv"
version = "0.4.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
lto = true

[dependencies]
ctrlc = "3.4.4"
clipboard-win = "5.3.1"
